### ISSUE TITLE
Pytorch support

### ISSUE THREAD

**Issue by AlexeyMatskevich** [pop-os/tensorman#38]
Are there any plans to support [pytorch docker](https://hub.docker.com/r/pytorch/pytorch)?

I tried to find any information on how to install any other frameworks on neural networks besides tensorflow, from the list that is advertised on the pop os site, but I could not find anything for version 22 of pop os.

I would love to know how to install PyTorch for example, since most models for machine vision, depth estimation, etc. are almost completely absent from Tensorflow.

**Comment by trawn3333** [comment]
Agree that some notes on this would be helpful. The site here indicates it's something that's supported out of the box but I'm not seeing it:

https://pop.system76.com/

I'm trying to create a modified tensorman image with it but am struggling to match the version of pytorch that tensorman/pip installs with what would be compatible with tensorman defaults.

**Comment by trawn3333** [comment]
I am beginning to think there are some catch 22's with respect to pytorch, tensorman, popos, and system76 hardware.

e.g. You'd need a pytorch that operates with sm_86 in order to be able to use newer NVIDIA hardware, but the latest tensorman can only target sm_70 and lower.

I think the tensorman project is a great idea but the capabilities it advertises are not accurately reflected to hardware currently being sold.

**Comment by AlexeyMatskevich** [comment]
I do not use this tool, and other than there has been no response, I have no desire to participate in future discussions on this issue. If anyone has a similar problem/concern, you are welcome to open a new issue.
